---
title: "Untitled"
output: github_document
date: "2022-08-16"
---

```{r setup, include=FALSE}
library(readxl)
Movies <- read_excel("~/git/movie-by-decade-/Movies.xlsx")
View(Movies)
library(readxl)
moviemoney <- read_excel("moviemoney.xlsx", 
    col_types = c("numeric", "skip", "skip", 
        "numeric", "date", "numeric", "numeric", 
        "text"))
View(moviemoney)
```

```{r,results='hide'}
library(dplyr)
library(tidyr)
library(ggfortify)
library(mltools)
library(data.table)
#disable Scientific notation 
options(scipen = 999)
```


```{r,}
Movies=mutate(Movies,"do people really mess with it like that "=dense_rank(vote_average))
```


```{r}
Movies$releasedate2=Movies$release_date%>%as.character()
```


```{r}
year=separate(Movies,releasedate2,c("date","year"),"-")
years=c()
```
```{r}

bigmovie=cbind(year["date"],Movies)
#merge by title 
#rename variable to merge 
names(bigmovie)[5]= "title"
damovie=merge(bigmovie,moviemoney,"title")


```
```{r}
#cleaned biggest movie to remove unnecessary data
biggestmovie$overview=NULL
biggestmovie$id=NULL
Hollywood <- subset(biggestmovie, select = -c(3))
names(year)[4]="title"
year$overview= NULL

year$numdate=as.numeric(year$date)
themovie=merge(year,Hollywood,"title")
```


```{r}
decade=data.frame(title=as.character(themovie$title))

decade$dec=themovie$numyear%%10*10
```


```{r}
newdata <- one_hot(as.data.table(decade))
decade$dec <- as.factor(decade$dec)
newdata <- one_hot(as.data.table(decade))


```
```{r}
  Hollywoo2=merge(newdata,Hollywood, by="title")
  hollydummdum=Hollywoo2[!duplicated(Hollywoo2), ]
```
  



```{r}
biggestmovie$gross=biggestmovie$revenue - biggestmovie$budget
```

```{r}
ggdistribution(dnorm,x = biggestmovie$budget,mean = mean(biggestmovie$budget),sd = sd(biggestmovie$budget))
ggdistribution(dnorm,x = biggestmovie$revenue,mean = mean(biggestmovie$revenue),sd = sd(biggestmovie$revenue))
```

```{r}

bslicedmovieten=biggestmovie%>%slice_min(budget,n=3518)
ggdistribution(dnorm,x = bslicedmovieten$budget,mean = mean(bslicedmovieten$budget),sd = sd(bslicedmovieten$budget))
rslicedmovierten=slice_min(biggestmovie,revenue,n=3518)
ggdistribution(dnorm,x = rslicedmovierten$budget,mean = mean(rslicedmovierten$budget),sd = sd(rslicedmovierten$budget))
```


```{r}
ggdistribution(pnorm,x = biggestmovie$budget,mean = mean(biggestmovie$budget),sd = sd(biggestmovie$budget))


```
```{r}
summary(lm(biggestmovie$budget~biggestmovie$revenue))

```
```{r}
summary(lm(bslicedmovieten$budget~bslicedmovieten$revenue))
```
```{r}
mean(biggestmovie$budget[biggestmovie$`1990s`==1])
```




